### PR TITLE
#162571291 Added view answers page(HTML landing page)

### PR DESCRIPTION
**Pull request by jmusila**
## What does this PR Do?
- Creates attendant landing page after login

## How should this be manually tested
steps for testing :

- Create a working folder on your desktop or preferred location.
- Navigate to your working folder and open a new terminal
- Type the following git clone https://github.com/jonathanmusila/Stack-Overflow.git
- Navigate to the UI and open index.html in a preferred browser.

## Screenshot:
stackoverflow-lite - google chrome_032

### CODE REVIEW

**Comment by wachiranduati** [comment]
looks good

**Comment by Ogutu-Brian** [comment]
Simple, and accurate UI. Thumbs up!

**Comment by SimonAwiti** [comment]
#### - Nice adherence to the naming conventions of your commit messages 
#### -Nice color combination on your UI

**Comment by tirgei** [comment]
Awesome

**Pull request merged**
