### PR TITLE
#162545306 A user can login

### PR DESCRIPTION
**Pull request by jmusila**
## What does this PR Do?
- Creates attendant landing page after login

## How should this be manually tested
steps for testing :

- Create a working folder on your desktop or preferred location.
- Navigate to your working folder and open a new terminal
- Type the following git clone https://github.com/jonathanmusila/Stack-Overflow.git
- Navigate to the UI and open index.html in a preferred browser then look for login button.

### Story-ID #162545306
Screenshot:
stackoverflow-lite - google chrome_033

### CODE REVIEW

**Comment by tirgei** [comment]
Nice UI. 

1 issue though, the title of your PR does not follow the Andela convention. For instance this one the title should be '{Story ID} A user can login'

**Comment by Siffersari** [comment]
Great UI. A user can be able to login by providing a username or email and password. That's clear. Good job. 
Maybe try add a link to the PT project incase someone want to delve deeper.

**Comment by Ogutu-Brian** [comment]
Nice UI, You could work on the distance between remember me text and the checkbox

**Comment by CaptainMumo** [comment]
Your 'What does this PR do?' does not seem to describe what we are seeing, it creates a log in page but you it creates a landing page after log in. Otherwise, good job

**Pull request merged**
